const axios = require("axios");
const { downloadContentFromMessage, getContentType } = require("@whiskeysockets/baileys");

// DEP_API_KEY - DO NOT CHANGE NAME
const DEP_API_KEY = process.env.DEP_API_KEY;

module.exports = {
    command: "deapi",
    category: "ai",
    description: "Generate images using DeAPI with DEP_API_KEY",

    async execute(m, sock, { args, userSettings }) {
        const style = userSettings?.style || 'normal';
        const prompt = args.join(" ").trim();

        const modes = {
            harsh: {
                react: "☣️",
                err: "☣️ 𝙋𝙍𝙊𝙑𝙄𝘿𝙀 𝙋𝙍𝙊𝙈𝙋𝙏 ☣️\n\n➤ Usage:.deapi cyberpunk cat",
                gen: "☣️ 𝙂𝙀𝙉𝙀𝙍𝘼𝙏𝙄𝙉𝙂 𝙑𝙄𝘼 𝘿𝙀𝘼𝙋𝙄... ⚡",
                done: "☣️ 𝙁𝙊𝙍𝙂𝙀𝘿 𝘽𝙔 𝘿𝙀𝘼𝙋𝙄 ☣️"
            },
            normal: {
                react: "🎨",
                err: "❌ Provide a prompt\n\n➤ Usage:.deapi anime girl with sword",
                gen: "🎨 Generating with DeAPI...",
                done: "🎨 Generated by DeAPI"
            },
            girl: {
                react: "💖",
                err: "🌸 𝑊𝑟𝑖𝑡𝑒 𝑤ℎ𝑎𝑡 𝑡𝑜 𝑔𝑒𝑛𝑒𝑟𝑎𝑡𝑒 𝑏𝑎𝑏𝑒~ 🍭\n\n➤ Usage:.deapi cute cat",
                gen: "💖 𝐶𝑟𝑒𝑎𝑡𝑖𝑛𝑔 𝑤𝑖𝑡ℎ 𝐷𝑒𝐴𝑃𝐼... ✨",
                done: "💖 𝑀𝑎𝑑𝑒 𝑏𝑦 𝐷𝑒𝐴𝑃𝐼 💎"
            }
        };

        const ui = modes[style] || modes.normal;

        if (!prompt) {
            await sock.sendMessage(m.chat, { react: { text: "❌", key: m.key } });
            return m.reply(ui.err);
        }

        if (!DEP_API_KEY) {
            await sock.sendMessage(m.chat, { react: { text: "🚫", key: m.key } });
            return m.reply("❌ DEP_API_KEY not found in environment. Add it to Render first.");
        }

        await sock.sendMessage(m.chat, {
            react: { text: ui.react, key: m.key }
        });

        const processMsg = await m.reply(ui.gen);

        try {
            // =========================
            // DEAPI CALL - USING DEP_API_KEY
            // =========================
            const response = await axios.post('https://api.deapi.com/v1/images/generations', {
                prompt: prompt,
                model: "deapi-xl-v1",
                size: "1024x1024",
                quality: "hd",
                n: 1
            }, {
                headers: {
                    'Authorization': `Bearer ${DEP_API_KEY}`,
                    'Content-Type': 'application/json',
                    'User-Agent': 'Vex-AI-Bot/1.0'
                },
                timeout: 60000
            });

            if (!response.data?.data?.[0]?.url) {
                throw new Error('No image URL returned from DeAPI');
            }

            const imageUrl = response.data.data[0].url;

            // Download image
            const imageResponse = await axios.get(imageUrl, {
                responseType: 'arraybuffer',
                timeout: 30000
            });

            const imageBuffer = Buffer.from(imageResponse.data);

            // Delete processing message
            try {
                await sock.sendMessage(m.chat, { delete: processMsg.key });
            } catch {}

            // Send result
            await sock.sendMessage(m.chat, {
                image: imageBuffer,
                caption: `${ui.done}\n\n*Prompt:* ${prompt}`
            }, { quoted: m });

        } catch (error) {
            console.log("DEAPI ERROR:", error.response?.data || error.message);

            let errorMsg = "❌ DeAPI failed. ";
            if (error.response?.status === 401) {
                errorMsg += "Invalid DEP_API_KEY.";
            } else if (error.response?.status === 429) {
                errorMsg += "Rate limit exceeded.";
            } else if (error.response?.status === 402) {
                errorMsg += "Insufficient credits.";
            } else {
                errorMsg += error.message.slice(0, 50);
            }

            try {
                await sock.sendMessage(m.chat, { delete: processMsg.key });
            } catch {}

            await sock.sendMessage(m.chat, {
                react: { text: "🚫", key: m.key }
            });

            return m.reply(errorMsg);
        }
    }
};
